// frontend-vue/src/views/RegisterPage.vue
<template>
  <div class="register-page container">
    <div class="register-container card">
      <div class="register-header">
        <h2>Crear Cuenta en <span class="highlight">AlojamientoMR</span></h2>
        <p>Regístrate para empezar a reservar</p>
      </div>

      <div v-if="success" class="success-message">
        <p>✅ ¡Registro exitoso! Ahora puedes iniciar sesión.</p>
        <router-link to="/login" class="btn-primary" style="display:inline-block;margin-top:1rem;">Ir a Login</router-link>
      </div>

      <form v-else @submit.prevent="handleRegister" class="register-form">
        <div class="form-group">
          <label for="nombreCompleto">Nombre Completo</label>
          <input type="text" id="nombreCompleto" v-model="form.nombreCompleto" required placeholder="Juan Pérez" />
        </div>

        <div class="form-group">
          <label for="email">Correo Electrónico</label>
          <input type="email" id="email" v-model="form.email" required placeholder="ejemplo@correo.com" />
        </div>

        <div class="form-group">
          <label for="password">Contraseña</label>
          <input type="password" id="password" v-model="form.password" required placeholder="Mínimo 8 caracteres" minlength="8" />
        </div>

        <div class="form-row">
          <div class="form-group">
            <label for="cedula">Cédula</label>
            <input type="text" id="cedula" v-model="form.cedula" required placeholder="1712345678" pattern="\d{10}" title="10 dígitos numéricos" />
          </div>
          <div class="form-group">
            <label for="telefono">Teléfono</label>
            <input type="text" id="telefono" v-model="form.telefono" required placeholder="0991234567" pattern="\d+" />
          </div>
        </div>

        <div class="form-group">
          <label for="domicilio">Domicilio</label>
          <input type="text" id="domicilio" v-model="form.domicilio" required placeholder="Av. Principal 123, Quito" />
        </div>

        <button type="submit" class="btn-primary register-btn" :disabled="loading">
          {{ loading ? 'Registrando...' : 'Crear Cuenta' }}
        </button>

        <div v-if="error" class="error-message">
          {{ error }}
        </div>
      </form>

      <div v-if="!success" class="register-footer">
        <p>¿Ya tienes una cuenta? <router-link to="/login">Inicia sesión</router-link></p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue';
import api from '@/services/api';

const form = reactive({
  nombreCompleto: '',
  email: '',
  password: '',
  cedula: '',
  telefono: '',
  domicilio: ''
});

const loading = ref(false);
const error = ref(null);
const success = ref(false);

const handleRegister = async () => {
  loading.value = true;
  error.value = null;

  try {
    await api.post('/usuarios/clientes/registrar', form);
    success.value = true;
  } catch (err) {
    const msg = err.response?.data?.message || err.response?.data?.errors?.[0] || 'Error al registrar. Verifica los datos e intenta nuevamente.';
    error.value = msg;
    console.error('Error registering:', err);
  } finally {
    loading.value = false;
  }
};
</script>

<style scoped>
.register-page {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: calc(100vh - 200px);
  padding: 2rem 1rem;
}

.register-container {
  width: 100%;
  max-width: 520px;
  padding: 3rem 2rem;
}

.register-header {
  text-align: center;
  margin-bottom: 2rem;
}

.register-header h2 {
  font-size: 1.75rem;
}

.register-header p {
  color: var(--color-text-secondary);
  margin-top: 0.5rem;
}

.form-group {
  margin-bottom: 1.25rem;
  flex: 1;
}

.form-group label {
  display: block;
  margin-bottom: 0.5rem;
  font-weight: 500;
  color: var(--color-text-primary);
}

.form-row {
  display: flex;
  gap: 1rem;
}

.register-btn {
  width: 100%;
  margin-top: 0.5rem;
}

.error-message {
  margin-top: 1rem;
  color: #e53935;
  background-color: #ffebee;
  padding: 0.75rem;
  border-radius: var(--radius-sm);
  text-align: center;
  font-size: 0.875rem;
}

.success-message {
  text-align: center;
  padding: 2rem;
  color: #2e7d32;
  background: #e8f5e9;
  border-radius: var(--radius-md);
}

.register-footer {
  margin-top: 2rem;
  text-align: center;
  font-size: 0.9rem;
}
</style>

// booking-frontend/src/pages/RegisterPage.jsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { HiOutlineUser, HiOutlineMail, HiOutlineLockClosed, HiOutlinePhone } from 'react-icons/hi';
import toast from 'react-hot-toast';
import api from '../services/api';
import './LoginPage.css';

export default function RegisterPage() {
  const [form, setForm] = useState({ nombreCompleto: '', email: '', password: '', confirmPassword: '', telefono: '' });
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const update = (field) => (e) => setForm({ ...form, [field]: e.target.value });

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!form.nombreCompleto || !form.email || !form.password) {
      toast.error('Nombre, email y contraseña son obligatorios.');
      return;
    }
    if (form.password !== form.confirmPassword) {
      toast.error('Las contraseñas no coinciden.');
      return;
    }
    if (form.password.length < 8) {
      toast.error('La contraseña debe tener al menos 8 caracteres.');
      return;
    }
    setLoading(true);
    try {
      await api.post('/clientes', {
        nombreCompleto: form.nombreCompleto,
        email: form.email,
        password: form.password,
        telefono: form.telefono || null,
      });
      toast.success('¡Cuenta creada exitosamente! Ahora inicia sesión.');
      navigate('/login');
    } catch (err) {
      const data = err.response?.data;
      if (data?.errors) {
        if (Array.isArray(data.errors)) {
          data.errors.forEach(error => toast.error(error));
        } else if (typeof data.errors === 'object') {
          Object.values(data.errors).flat().forEach(error => toast.error(error));
        }
      } else if (data?.errores && Array.isArray(data.errores)) {
        data.errores.forEach(error => toast.error(error));
      } else {
        const msg = data?.message || data?.Message || data?.mensaje || data?.Mensaje || 'Error al crear la cuenta.';
        toast.error(msg);
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-page">
      <div className="login-card animate-fade-in-up">
        <div className="login-header">
          <span className="brand-icon">✦</span>
          <h1>Crear Cuenta</h1>
          <p>Regístrate para reservar propiedades</p>
        </div>

        <form onSubmit={handleSubmit} className="login-form">
          <div className="form-group">
            <label className="input-label">Nombre Completo *</label>
            <div className="input-with-icon">
              <HiOutlineUser className="input-icon" />
              <input type="text" className="input-field" placeholder="Juan Pérez" value={form.nombreCompleto} onChange={update('nombreCompleto')} />
            </div>
          </div>

          <div className="form-group">
            <label className="input-label">Correo Electrónico *</label>
            <div className="input-with-icon">
              <HiOutlineMail className="input-icon" />
              <input type="email" className="input-field" placeholder="correo@ejemplo.com" value={form.email} onChange={update('email')} autoComplete="email" />
            </div>
          </div>

          <div className="form-row">
            <div className="form-group">
              <label className="input-label">Contraseña *</label>
              <div className="input-with-icon">
                <HiOutlineLockClosed className="input-icon" />
                <input type="password" className="input-field" placeholder="••••••••" value={form.password} onChange={update('password')} />
              </div>
            </div>
            <div className="form-group">
              <label className="input-label">Confirmar Contraseña *</label>
              <div className="input-with-icon">
                <HiOutlineLockClosed className="input-icon" />
                <input type="password" className="input-field" placeholder="••••••••" value={form.confirmPassword} onChange={update('confirmPassword')} />
              </div>
            </div>
          </div>

          <div className="form-group">
            <label className="input-label">Teléfono (opcional)</label>
            <div className="input-with-icon">
              <HiOutlinePhone className="input-icon" />
              <input type="tel" className="input-field" placeholder="+51 999 999 999" value={form.telefono} onChange={update('telefono')} />
            </div>
          </div>

          <button type="submit" className="btn btn-primary login-btn" disabled={loading}>
            {loading ? 'Creando cuenta...' : 'Registrarme'}
          </button>
        </form>

        <div className="login-footer">
          <p>¿Ya tienes cuenta? <Link to="/login">Iniciar Sesión</Link></p>
        </div>
      </div>
    </div>
  );
}
