// booking-frontend/src/pages/LoginPage.jsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { HiOutlineMail, HiOutlineLockClosed } from 'react-icons/hi';
import toast from 'react-hot-toast';
import { authApi } from '../api/auth.api';
import useAuthStore from '../store/useAuthStore';
import './LoginPage.css';

export default function LoginPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const login = useAuthStore((s) => s.login);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!email || !password) {
      toast.error('Por favor completa todos los campos.');
      return;
    }
    setLoading(true);
    try {
      const { data } = await authApi.login({ email, password });
      await login(data.datos);
      toast.success(`¡Bienvenido, ${data.datos.nombreCompleto}!`);
      
      // Redirección basada en rol
      if (data.datos.roles && data.datos.roles.includes('Administrador')) {
        navigate('/admin');
      } else {
        navigate('/');
      }
    } catch (err) {
      const data = err.response?.data;
      const msg = data?.message || data?.Message || data?.mensaje || data?.Mensaje || 'Credenciales inválidas.';
      toast.error(msg);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-page">
      <div className="login-card animate-fade-in-up">
        <div className="login-header">
          <span className="brand-icon">✦</span>
          <h1>Iniciar Sesión</h1>
          <p>Accede a tu cuenta para gestionar reservas</p>
        </div>

        <form onSubmit={handleSubmit} className="login-form">
          <div className="form-group">
            <label className="input-label">Correo Electrónico</label>
            <div className="input-with-icon">
              <HiOutlineMail className="input-icon" />
              <input
                type="email"
                className="input-field"
                placeholder="correo@ejemplo.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                autoComplete="email"
              />
            </div>
          </div>

          <div className="form-group">
            <label className="input-label">Contraseña</label>
            <div className="input-with-icon">
              <HiOutlineLockClosed className="input-icon" />
              <input
                type="password"
                className="input-field"
                placeholder="••••••••"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                autoComplete="current-password"
              />
            </div>
          </div>

          <button type="submit" className="btn btn-primary login-btn" disabled={loading}>
            {loading ? 'Autenticando...' : 'Ingresar'}
          </button>
        </form>

        <div className="login-footer">
          <p>¿No tienes cuenta? <Link to="/register">Regístrate aquí</Link></p>
        </div>
      </div>
    </div>
  );
}

// frontend-vue/src/views/LoginPage.vue
<template>
  <div class="login-page container">
    <div class="login-container card">
      <div class="login-header">
        <h2>Bienvenido a <span class="highlight">AlojamientoMR</span></h2>
        <p>Ingresa tus credenciales para continuar</p>
      </div>

      <form @submit.prevent="handleLogin" class="login-form">
        <div class="form-group">
          <label for="email">Correo Electrónico</label>
          <input 
            type="email" 
            id="email" 
            v-model="email" 
            required 
            placeholder="ejemplo@correo.com"
          />
        </div>

        <div class="form-group">
          <label for="password">Contraseña</label>
          <input 
            type="password" 
            id="password" 
            v-model="password" 
            required 
            placeholder="********"
          />
        </div>

        <button type="submit" class="btn-primary login-btn" :disabled="loading">
          {{ loading ? 'Iniciando sesión...' : 'Ingresar' }}
        </button>

        <div v-if="error" class="error-message">
          {{ error }}
        </div>
      </form>

      <div class="login-footer">
        <p>¿No tienes una cuenta? <router-link to="/register">Regístrate aquí</router-link></p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useAuthStore } from '@/store/auth';
import { useRouter } from 'vue-router';

const email = ref('');
const password = ref('');
const loading = ref(false);
const error = ref(null);

const authStore = useAuthStore();
const router = useRouter();

const handleLogin = async () => {
  loading.value = true;
  error.value = null;
  
  try {
    await authStore.login({ email: email.value, password: password.value });
    router.push(authStore.isAdmin ? '/admin' : '/');
  } catch (err) {
    error.value = 'Credenciales inválidas. Por favor, intenta nuevamente.';
    console.error('Error logging in:', err);
  } finally {
    loading.value = false;
  }
};
</script>

<style scoped>
.login-page {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: calc(100vh - 200px);
}

.login-container {
  width: 100%;
  max-width: 450px;
  padding: 3rem 2rem;
}

.login-header {
  text-align: center;
  margin-bottom: 2rem;
}

.login-header h2 {
  font-size: 1.75rem;
}

.login-header p {
  color: var(--color-text-secondary);
  margin-top: 0.5rem;
}

.form-group {
  margin-bottom: 1.5rem;
}

.form-group label {
  display: block;
  margin-bottom: 0.5rem;
  font-weight: 500;
  color: var(--color-text-primary);
}

.login-btn {
  width: 100%;
  margin-top: 1rem;
}

.error-message {
  margin-top: 1rem;
  color: #e53935;
  background-color: #ffebee;
  padding: 0.75rem;
  border-radius: var(--radius-sm);
  text-align: center;
  font-size: 0.875rem;
}

.login-footer {
  margin-top: 2rem;
  text-align: center;
  font-size: 0.9rem;
}
</style>
